# This workflow integrates Scan with GitHub's code scanning feature
# Scan is a free open-source security tool for modern DevOps teams from ShiftLeft
# Visit https://slscan.io/en/latest/integrations/code-scan for help
name: SL Scanning

# This section configures the trigger for the workflow. Feel free to customize depending on your convention
on: 
 # push:
    
  pull_request:
    # The branches below must be a subset of the branches above
   # branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  

  Scan-test:
    # Scan runs on ubuntu, mac and windows
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # Instructions
    # 1. Setup JDK, Node.js, Python etc depending on your project type
    # 2. Compile or build the project before invoking scan
    #    Example: mvn compile, or npm install or pip install goes here
    # 3. Invoke Scan with the github token. Leave the workspace empty to use relative url

    - name: Self dep-scan
      uses: AppThreat/dep-scan-action@master
